version: "3.9"

networks:
  main:
    external: true

services:
  q-api-gateway-app:
    container_name: q-api-gateway-app
    build: .
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    networks:
      - main

  postgresql:
    container_name: postgresql
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - main

volumes:
  postgres-db: